// Package algocodeclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package algocodeclient

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for StatementVariantFormat.
const (
	Md  StatementVariantFormat = "md"
	Pdf StatementVariantFormat = "pdf"
)

// Valid indicates whether the value is a known member of the StatementVariantFormat enum.
func (e StatementVariantFormat) Valid() bool {
	switch e {
	case Md:
		return true
	case Pdf:
		return true
	default:
		return false
	}
}

// Defines values for StatementVariantLanguage.
const (
	En StatementVariantLanguage = "en"
	Ro StatementVariantLanguage = "ro"
)

// Valid indicates whether the value is a known member of the StatementVariantLanguage enum.
func (e StatementVariantLanguage) Valid() bool {
	switch e {
	case En:
		return true
	case Ro:
		return true
	default:
		return false
	}
}

// ApiContest defines model for ApiContest.
type ApiContest struct {
	// Schema A URL to the JSON Schema for this object.
	Schema                    *string      `json:"$schema,omitempty"`
	CreatedAt                 time.Time    `json:"created_at"`
	Description               string       `json:"description"`
	Editors                   *[]UserBrief `json:"editors"`
	EndTime                   time.Time    `json:"end_time"`
	IcpcSubmissionPenalty     int64        `json:"icpc_submission_penalty"`
	Id                        int64        `json:"id"`
	LeaderboardAdvancedFilter bool         `json:"leaderboard_advanced_filter"`
	LeaderboardFreeze         *time.Time   `json:"leaderboard_freeze"`
	LeaderboardStyle          string       `json:"leaderboard_style"`
	MaxSubs                   int64        `json:"max_subs"`
	MentorOnly                bool         `json:"mentor_only"`
	Name                      string       `json:"name"`
	PerUserTime               int64        `json:"per_user_time"`
	PublicJoin                bool         `json:"public_join"`
	PublicLeaderboard         bool         `json:"public_leaderboard"`
	QuestionCooldown          int64        `json:"question_cooldown"`
	RegisterDuringContest     bool         `json:"register_during_contest"`
	StartTime                 time.Time    `json:"start_time"`
	SubmissionCooldown        int64        `json:"submission_cooldown"`
	Testers                   *[]UserBrief `json:"testers"`
	Type                      string       `json:"type"`
	Visible                   bool         `json:"visible"`
}

// ApiProblem defines model for ApiProblem.
type ApiProblem struct {
	// Schema A URL to the JSON Schema for this object.
	Schema                 *string             `json:"$schema,omitempty"`
	Category               *string             `json:"category"`
	CategoryClass          *string             `json:"category_class"`
	CommunicationProcesses int64               `json:"communication_processes"`
	ConsoleInput           bool                `json:"console_input"`
	CreatedAt              time.Time           `json:"created_at"`
	DefaultIdeLanguage     string              `json:"default_ide_language"`
	DefaultPoints          any              `json:"default_points"`
	Difficulty             string              `json:"difficulty"`
	Id                     int64               `json:"id"`
	MemoryLimit            int64               `json:"memory_limit"`
	Name                   string              `json:"name"`
	PublishedAt            *time.Time          `json:"published_at"`
	ScorePrecision         int32               `json:"score_precision"`
	ScoreScale             any              `json:"score_scale"`
	ScoringStrategy        string              `json:"scoring_strategy"`
	SourceCredits          string              `json:"source_credits"`
	SourceSize             int64               `json:"source_size"`
	StatementVariants      *[]StatementVariant `json:"statementVariants"`
	SubmitLanguages        *[]Language         `json:"submitLanguages"`
	Tags                   *[]Tag              `json:"tags"`
	TaskType               string              `json:"task_type"`
	TestName               string              `json:"test_name"`
	TimeLimit              float64             `json:"time_limit"`
	Visible                bool                `json:"visible"`
	VisibleTests           bool                `json:"visible_tests"`
}

// ContestGetInputBody defines model for ContestGetInputBody.
type ContestGetInputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema   *string `json:"$schema,omitempty"`
	EditorId *int64  `json:"editor_id,omitempty"`
	Ended    *bool   `json:"ended,omitempty"`
	Future   *bool   `json:"future,omitempty"`
	Limit    *int64  `json:"limit,omitempty"`
	Offset   *int64  `json:"offset,omitempty"`
	Running  *bool   `json:"running,omitempty"`
	Type     *string `json:"type,omitempty"`
}

// ContestSearchResult defines model for ContestSearchResult.
type ContestSearchResult struct {
	// Schema A URL to the JSON Schema for this object.
	Schema   *string       `json:"$schema,omitempty"`
	Contests *[]ApiContest `json:"contests"`
}

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	// Location Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
	Location *string `json:"location,omitempty"`

	// Message Error message text
	Message *string `json:"message,omitempty"`

	// Value The value at the given location
	Value interface{} `json:"value,omitempty"`
}

// ErrorModel defines model for ErrorModel.
type ErrorModel struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`

	// Detail A human-readable explanation specific to this occurrence of the problem.
	Detail *string `json:"detail,omitempty"`

	// Errors Optional list of individual error details
	Errors *[]ErrorDetail `json:"errors,omitempty"`

	// Instance A URI reference that identifies the specific occurrence of the problem.
	Instance *string `json:"instance,omitempty"`

	// Status HTTP status code
	Status *int64 `json:"status,omitempty"`

	// Title A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
	Title *string `json:"title,omitempty"`

	// Type A URI reference to human-readable documentation for the error.
	Type *string `json:"type,omitempty"`
}

// FullSearchProblem defines model for FullSearchProblem.
type FullSearchProblem struct {
	AttemptedBy        int64      `json:"attempted_by"`
	Category           *string    `json:"category"`
	CategoryClass      *string    `json:"category_class"`
	CreatedAt          time.Time  `json:"created_at"`
	DefaultIdeLanguage string     `json:"default_ide_language"`
	Difficulty         string     `json:"difficulty"`
	Id                 int64      `json:"id"`
	IsEditor           bool       `json:"is_editor"`
	MaxScore           *string    `json:"max_score"`
	MemoryLimit        int64      `json:"memory_limit"`
	Name               string     `json:"name"`
	PublishedAt        *time.Time `json:"published_at"`
	ScoreUserId        *int64     `json:"score_user_id"`
	SolvedBy           int64      `json:"solved_by"`
	SourceCredits      string     `json:"source_credits"`
	SourceSize         int64      `json:"source_size"`
	Tags               *[]Tag     `json:"tags"`
	TaskType           string     `json:"task_type"`
	TimeLimit          float64    `json:"time_limit"`
	Visible            bool       `json:"visible"`
	VisibleTests       bool       `json:"visible_tests"`
}

// Language defines model for Language.
type Language struct {
	InternalName  string `json:"internal_name"`
	PrintableName string `json:"printable_name"`
}

// Problem defines model for Problem.
type Problem struct {
	Category               *string    `json:"category"`
	CategoryClass          *string    `json:"category_class"`
	CommunicationProcesses int64      `json:"communication_processes"`
	ConsoleInput           bool       `json:"console_input"`
	CreatedAt              time.Time  `json:"created_at"`
	DefaultIdeLanguage     string     `json:"default_ide_language"`
	DefaultPoints          any     `json:"default_points"`
	Difficulty             string     `json:"difficulty"`
	Id                     int64      `json:"id"`
	MemoryLimit            int64      `json:"memory_limit"`
	Name                   string     `json:"name"`
	PublishedAt            *time.Time `json:"published_at"`
	ScorePrecision         int32      `json:"score_precision"`
	ScoreScale             any     `json:"score_scale"`
	ScoringStrategy        string     `json:"scoring_strategy"`
	SourceCredits          string     `json:"source_credits"`
	SourceSize             int64      `json:"source_size"`
	TaskType               string     `json:"task_type"`
	TestName               string     `json:"test_name"`
	TimeLimit              float64    `json:"time_limit"`
	Visible                bool       `json:"visible"`
	VisibleTests           bool       `json:"visible_tests"`
}

// ProblemAITutorConfig defines model for ProblemAITutorConfig.
type ProblemAITutorConfig struct {
	CommonMistakes          *[]string   `json:"common_mistakes"`
	CreatedAt               time.Time   `json:"created_at"`
	Enabled                 bool        `json:"enabled"`
	HintLadder              interface{} `json:"hint_ladder"`
	MentorNotes             string      `json:"mentor_notes"`
	Model                   string      `json:"model"`
	OfficialSolutionSummary string      `json:"official_solution_summary"`
	ProblemContext          string      `json:"problem_context"`
	ProblemId               int64       `json:"problem_id"`
	RevealPolicy            string      `json:"reveal_policy"`
	SystemPolicy            string      `json:"system_policy"`
	UpdatedAt               time.Time   `json:"updated_at"`
	UpdatedBy               *int64      `json:"updated_by,omitempty"`
}

// ProblemEducationBundle defines model for ProblemEducationBundle.
type ProblemEducationBundle struct {
	// Schema A URL to the JSON Schema for this object.
	Schema                  *string                    `json:"$schema,omitempty"`
	AiTutor                 *ProblemAITutorConfig      `json:"ai_tutor,omitempty"`
	AiTutorAvailable        bool                       `json:"ai_tutor_available"`
	LockedOfficialSolutions int64                      `json:"locked_official_solutions"`
	Metadata                *ProblemEducationMetadata  `json:"metadata,omitempty"`
	OfficialSolutions       *[]ProblemOfficialSolution `json:"official_solutions"`
	Tutorials               *[]ProblemTutorial         `json:"tutorials"`
}

// ProblemEducationMetadata defines model for ProblemEducationMetadata.
type ProblemEducationMetadata struct {
	AlgolympLessonIndex *int64    `json:"algolymp_lesson_index,omitempty"`
	AlgolympLessonTitle string    `json:"algolymp_lesson_title"`
	AlgolympMaterialUrl string    `json:"algolymp_material_url"`
	AlgolympProgramId   *int64    `json:"algolymp_program_id,omitempty"`
	AlgolympVideoId     string    `json:"algolymp_video_id"`
	CreatedAt           time.Time `json:"created_at"`
	EstimatedDifficulty string    `json:"estimated_difficulty"`
	Grade               string    `json:"grade"`
	Level               string    `json:"level"`
	MentorNotes         string    `json:"mentor_notes"`
	Prerequisites       *[]string `json:"prerequisites"`
	PrimaryTopic        string    `json:"primary_topic"`
	ProblemId           int64     `json:"problem_id"`
	Program             string    `json:"program"`
	QualityStatus       string    `json:"quality_status"`
	Role                string    `json:"role"`
	SecondaryTopics     *[]string `json:"secondary_topics"`
	SourceSlug          string    `json:"source_slug"`
	SourceType          string    `json:"source_type"`
	SourceUrl           string    `json:"source_url"`
	UpdatedAt           time.Time `json:"updated_at"`
	UpdatedBy           *int64    `json:"updated_by,omitempty"`
}

// ProblemGetInputBody defines model for ProblemGetInputBody.
type ProblemGetInputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema             *string     `json:"$schema,omitempty"`
	Category           *string     `json:"category,omitempty"`
	CategoryClass      *string     `json:"category_class,omitempty"`
	Descending         *bool       `json:"descending,omitempty"`
	Difficulty         *string     `json:"difficulty,omitempty"`
	Ids                *[]int64    `json:"ids,omitempty"`
	Lang               *string     `json:"lang,omitempty"`
	Limit              *int64      `json:"limit,omitempty"`
	Name               *string     `json:"name,omitempty"`
	NameFuzzy          *string     `json:"name_fuzzy,omitempty"`
	Offset             *int64      `json:"offset,omitempty"`
	Ordering           *string     `json:"ordering,omitempty"`
	ScoreUserId        *int64      `json:"score_user_id,omitempty"`
	Tags               *[]TagGroup `json:"tags,omitempty"`
	TranslationFlagged *bool       `json:"translation_flagged,omitempty"`
}

// ProblemOfficialSolution defines model for ProblemOfficialSolution.
type ProblemOfficialSolution struct {
	Code             string    `json:"code"`
	Complexity       string    `json:"complexity"`
	CreatedAt        time.Time `json:"created_at"`
	CreatedBy        *int64    `json:"created_by,omitempty"`
	Id               int64     `json:"id"`
	Language         string    `json:"language"`
	Markdown         string    `json:"markdown"`
	ProblemId        int64     `json:"problem_id"`
	Status           string    `json:"status"`
	Title            string    `json:"title"`
	UpdatedAt        time.Time `json:"updated_at"`
	UpdatedBy        *int64    `json:"updated_by,omitempty"`
	VisibilityPolicy string    `json:"visibility_policy"`
}

// ProblemSearchResult defines model for ProblemSearchResult.
type ProblemSearchResult struct {
	// Schema A URL to the JSON Schema for this object.
	Schema   *string              `json:"$schema,omitempty"`
	Count    int64                `json:"count"`
	Problems *[]FullSearchProblem `json:"problems"`
}

// ProblemStatementContent defines model for ProblemStatementContent.
type ProblemStatementContent struct {
	// Schema A URL to the JSON Schema for this object.
	Schema   *string `json:"$schema,omitempty"`
	Content  string  `json:"content"`
	Format   string  `json:"format"`
	Language *string `json:"language,omitempty"`
	Type     *string `json:"type,omitempty"`
}

// ProblemTutorial defines model for ProblemTutorial.
type ProblemTutorial struct {
	AlgolympVideoId string    `json:"algolymp_video_id"`
	CreatedAt       time.Time `json:"created_at"`
	CreatedBy       *int64    `json:"created_by,omitempty"`
	Id              int64     `json:"id"`
	Language        string    `json:"language"`
	Markdown        string    `json:"markdown"`
	ProblemId       int64     `json:"problem_id"`
	Status          string    `json:"status"`
	Title           string    `json:"title"`
	UpdatedAt       time.Time `json:"updated_at"`
	UpdatedBy       *int64    `json:"updated_by,omitempty"`
	VideoUrl        string    `json:"video_url"`
}

// ScoredProblem defines model for ScoredProblem.
type ScoredProblem struct {
	Category               *string    `json:"category"`
	CategoryClass          *string    `json:"category_class"`
	CommunicationProcesses int64      `json:"communication_processes"`
	ConsoleInput           bool       `json:"console_input"`
	CreatedAt              time.Time  `json:"created_at"`
	DefaultIdeLanguage     string     `json:"default_ide_language"`
	DefaultPoints          string     `json:"default_points"`
	Difficulty             string     `json:"difficulty"`
	Id                     int64      `json:"id"`
	IsEditor               bool       `json:"is_editor"`
	MaxScore               *string    `json:"max_score"`
	MemoryLimit            int64      `json:"memory_limit"`
	Name                   string     `json:"name"`
	PublishedAt            *time.Time `json:"published_at"`
	ScorePrecision         int32      `json:"score_precision"`
	ScoreScale             string     `json:"score_scale"`
	ScoreUserId            *int64     `json:"score_user_id"`
	ScoringStrategy        string     `json:"scoring_strategy"`
	SourceCredits          string     `json:"source_credits"`
	SourceSize             int64      `json:"source_size"`
	TaskType               string     `json:"task_type"`
	TestName               string     `json:"test_name"`
	TimeLimit              float64    `json:"time_limit"`
	Visible                bool       `json:"visible"`
	VisibleTests           bool       `json:"visible_tests"`
}

// StatementVariant defines model for StatementVariant.
type StatementVariant struct {
	// Format Statement format. Markdown is the recommended one to interpret, as PDFs are usually served only for historical purposes.
	Format StatementVariantFormat `json:"format"`

	// Language Statement language
	Language StatementVariantLanguage `json:"language"`

	// LastUpdatedAt Last updated time of the underlying file for the statement.
	LastUpdatedAt time.Time `json:"lastUpdatedAt"`

	// Permalink Link to the statement's contents, raw. It is not guaranteed that this URL will remain the same.
	Permalink string `json:"permalink"`

	// RenderURL For markdown statements, this URL represents the HTML rendered version of this statement. See additional documentation for how to correctly render the HTML. It is not guaranteed that this URL will remain the same.
	RenderURL string `json:"renderURL"`

	// Type Usually empty, can be used to distinguish between multiple loose types of variants.
	Type string `json:"type"`
}

// StatementVariantFormat Statement format. Markdown is the recommended one to interpret, as PDFs are usually served only for historical purposes.
type StatementVariantFormat string

// StatementVariantLanguage Statement language
type StatementVariantLanguage string

// Submission defines model for Submission.
type Submission struct {
	CodeSize       int64     `json:"code_size"`
	CompileError   *bool     `json:"compile_error"`
	CompileMessage *string   `json:"compile_message,omitempty"`
	CompileTime    *float64  `json:"compile_time"`
	ContestId      *int64    `json:"contest_id"`
	CreatedAt      time.Time `json:"created_at"`
	IcpcVerdict    *string   `json:"icpc_verdict"`
	Id             int64     `json:"id"`
	Language       string    `json:"language"`
	MaxMemory      int64     `json:"max_memory"`
	MaxTime        float64   `json:"max_time"`
	ProblemId      int64     `json:"problem_id"`
	Score          any    `json:"score"`
	ScorePrecision int32     `json:"score_precision"`
	ScoreScale     any    `json:"score_scale"`
	Status         string    `json:"status"`
	SubmissionType string    `json:"submission_type"`
	UserId         int64     `json:"user_id"`
}

// SubmissionListInputBody defines model for SubmissionListInputBody.
type SubmissionListInputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema        *string  `json:"$schema,omitempty"`
	Ascending     *bool    `json:"ascending,omitempty"`
	CompileError  *bool    `json:"compile_error,omitempty"`
	ContestId     *int64   `json:"contest_id,omitempty"`
	FromAuthors   *bool    `json:"from_authors,omitempty"`
	Id            *int64   `json:"id,omitempty"`
	Ids           *[]int64 `json:"ids,omitempty"`
	Lang          *string  `json:"lang,omitempty"`
	Limit         *int64   `json:"limit,omitempty"`
	Offset        *int64   `json:"offset,omitempty"`
	Ordering      *string  `json:"ordering,omitempty"`
	ProblemId     *int64   `json:"problem_id,omitempty"`
	ProblemIds    *[]int64 `json:"problem_ids,omitempty"`
	ProblemListId *int64   `json:"problem_list_id,omitempty"`
	Status        *string  `json:"status,omitempty"`
	UserId        *int64   `json:"user_id,omitempty"`
	UserIds       *[]int64 `json:"user_ids,omitempty"`
	Waiting       *bool    `json:"waiting,omitempty"`
}

// Submissions defines model for Submissions.
type Submissions struct {
	// Schema A URL to the JSON Schema for this object.
	Schema         *string              `json:"$schema,omitempty"`
	Count          int64                `json:"count"`
	Problems       map[string]Problem   `json:"problems"`
	Submissions    *[]Submission        `json:"submissions"`
	TruncatedCount bool                 `json:"truncated_count"`
	Users          map[string]UserBrief `json:"users"`
}

// Tag defines model for Tag.
type Tag struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
	Type string `json:"type"`
}

// TagGroup defines model for TagGroup.
type TagGroup struct {
	Negate bool     `json:"negate"`
	TagIds *[]int64 `json:"tag_ids"`
}

// UserBrief defines model for UserBrief.
type UserBrief struct {
	Admin       bool   `json:"admin"`
	DisplayName string `json:"display_name"`
	Generated   bool   `json:"generated"`
	Id          int64  `json:"id"`
	Mentor      bool   `json:"mentor"`
	Name        string `json:"name"`
	Proposer    bool   `json:"proposer"`
}

// UsersGetInputBody defines model for UsersGetInputBody.
type UsersGetInputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema    *string  `json:"$schema,omitempty"`
	Ids       *[]int64 `json:"ids,omitempty"`
	Limit     *int64   `json:"limit,omitempty"`
	Name      *string  `json:"name,omitempty"`
	NameFuzzy *string  `json:"name_fuzzy,omitempty"`
	Offset    *int64   `json:"offset,omitempty"`
}

// UsersGetOutputBody defines model for UsersGetOutputBody.
type UsersGetOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema     *string      `json:"$schema,omitempty"`
	TotalCount int64        `json:"total_count"`
	Users      *[]UserBrief `json:"users"`
}

// bearerContextKey is the context key for bearer security scheme
type bearerContextKey string

// PublicGetProblemStatementParams defines parameters for PublicGetProblemStatement.
type PublicGetProblemStatementParams struct {
	// Lang Preferred statement language, usually 'en' or 'ro'.
	Lang *string `form:"lang,omitempty" json:"lang,omitempty"`
}

// PublicGetContestsJSONRequestBody defines body for PublicGetContests for application/json ContentType.
type PublicGetContestsJSONRequestBody = ContestGetInputBody

// PublicGetProblemsJSONRequestBody defines body for PublicGetProblems for application/json ContentType.
type PublicGetProblemsJSONRequestBody = ProblemGetInputBody

// PublicGetSubmissionsJSONRequestBody defines body for PublicGetSubmissions for application/json ContentType.
type PublicGetSubmissionsJSONRequestBody = SubmissionListInputBody

// PublicGetUsersJSONRequestBody defines body for PublicGetUsers for application/json ContentType.
type PublicGetUsersJSONRequestBody = UsersGetInputBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PublicGetContestsWithBody request with any body
	PublicGetContestsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PublicGetContests(ctx context.Context, body PublicGetContestsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PublicGetContestById request
	PublicGetContestById(ctx context.Context, contestID int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PublicGetContestProblems request
	PublicGetContestProblems(ctx context.Context, contestID int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PublicGetProblemsWithBody request with any body
	PublicGetProblemsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PublicGetProblems(ctx context.Context, body PublicGetProblemsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PublicGetProblemById request
	PublicGetProblemById(ctx context.Context, problemID int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PublicGetProblemEducation request
	PublicGetProblemEducation(ctx context.Context, problemID int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PublicGetProblemStatement request
	PublicGetProblemStatement(ctx context.Context, problemID int, params *PublicGetProblemStatementParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PublicGetProblemStatementVariants request
	PublicGetProblemStatementVariants(ctx context.Context, problemID int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PublicGetProblemTags request
	PublicGetProblemTags(ctx context.Context, problemID int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PublicGetPlatformStats request
	PublicGetPlatformStats(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PublicGetSubmissionsWithBody request with any body
	PublicGetSubmissionsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PublicGetSubmissions(ctx context.Context, body PublicGetSubmissionsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PublicGetTags request
	PublicGetTags(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PublicGetUsersWithBody request with any body
	PublicGetUsersWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PublicGetUsers(ctx context.Context, body PublicGetUsersJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PublicGetContestsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPublicGetContestsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PublicGetContests(ctx context.Context, body PublicGetContestsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPublicGetContestsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PublicGetContestById(ctx context.Context, contestID int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPublicGetContestByIdRequest(c.Server, contestID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PublicGetContestProblems(ctx context.Context, contestID int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPublicGetContestProblemsRequest(c.Server, contestID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PublicGetProblemsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPublicGetProblemsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PublicGetProblems(ctx context.Context, body PublicGetProblemsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPublicGetProblemsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PublicGetProblemById(ctx context.Context, problemID int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPublicGetProblemByIdRequest(c.Server, problemID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PublicGetProblemEducation(ctx context.Context, problemID int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPublicGetProblemEducationRequest(c.Server, problemID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PublicGetProblemStatement(ctx context.Context, problemID int, params *PublicGetProblemStatementParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPublicGetProblemStatementRequest(c.Server, problemID, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PublicGetProblemStatementVariants(ctx context.Context, problemID int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPublicGetProblemStatementVariantsRequest(c.Server, problemID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PublicGetProblemTags(ctx context.Context, problemID int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPublicGetProblemTagsRequest(c.Server, problemID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PublicGetPlatformStats(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPublicGetPlatformStatsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PublicGetSubmissionsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPublicGetSubmissionsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PublicGetSubmissions(ctx context.Context, body PublicGetSubmissionsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPublicGetSubmissionsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PublicGetTags(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPublicGetTagsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PublicGetUsersWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPublicGetUsersRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PublicGetUsers(ctx context.Context, body PublicGetUsersJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPublicGetUsersRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPublicGetContestsRequest calls the generic PublicGetContests builder with application/json body
func NewPublicGetContestsRequest(server string, body PublicGetContestsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPublicGetContestsRequestWithBody(server, "application/json", bodyReader)
}

// NewPublicGetContestsRequestWithBody generates requests for PublicGetContests with any type of body
func NewPublicGetContestsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/contests")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPublicGetContestByIdRequest generates requests for PublicGetContestById
func NewPublicGetContestByIdRequest(server string, contestID int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "contestID", contestID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/contests/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPublicGetContestProblemsRequest generates requests for PublicGetContestProblems
func NewPublicGetContestProblemsRequest(server string, contestID int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "contestID", contestID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/contests/%s/problems", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPublicGetProblemsRequest calls the generic PublicGetProblems builder with application/json body
func NewPublicGetProblemsRequest(server string, body PublicGetProblemsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPublicGetProblemsRequestWithBody(server, "application/json", bodyReader)
}

// NewPublicGetProblemsRequestWithBody generates requests for PublicGetProblems with any type of body
func NewPublicGetProblemsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/problems")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPublicGetProblemByIdRequest generates requests for PublicGetProblemById
func NewPublicGetProblemByIdRequest(server string, problemID int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "problemID", problemID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/problems/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPublicGetProblemEducationRequest generates requests for PublicGetProblemEducation
func NewPublicGetProblemEducationRequest(server string, problemID int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "problemID", problemID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/problems/%s/education", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPublicGetProblemStatementRequest generates requests for PublicGetProblemStatement
func NewPublicGetProblemStatementRequest(server string, problemID int, params *PublicGetProblemStatementParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "problemID", problemID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/problems/%s/statement", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Lang != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", false, "lang", *params.Lang, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPublicGetProblemStatementVariantsRequest generates requests for PublicGetProblemStatementVariants
func NewPublicGetProblemStatementVariantsRequest(server string, problemID int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "problemID", problemID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/problems/%s/statements", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPublicGetProblemTagsRequest generates requests for PublicGetProblemTags
func NewPublicGetProblemTagsRequest(server string, problemID int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "problemID", problemID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/problems/%s/tags", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPublicGetPlatformStatsRequest generates requests for PublicGetPlatformStats
func NewPublicGetPlatformStatsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/stats/platform")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPublicGetSubmissionsRequest calls the generic PublicGetSubmissions builder with application/json body
func NewPublicGetSubmissionsRequest(server string, body PublicGetSubmissionsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPublicGetSubmissionsRequestWithBody(server, "application/json", bodyReader)
}

// NewPublicGetSubmissionsRequestWithBody generates requests for PublicGetSubmissions with any type of body
func NewPublicGetSubmissionsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/submissions")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPublicGetTagsRequest generates requests for PublicGetTags
func NewPublicGetTagsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/tags")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPublicGetUsersRequest calls the generic PublicGetUsers builder with application/json body
func NewPublicGetUsersRequest(server string, body PublicGetUsersJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPublicGetUsersRequestWithBody(server, "application/json", bodyReader)
}

// NewPublicGetUsersRequestWithBody generates requests for PublicGetUsers with any type of body
func NewPublicGetUsersRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/users")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PublicGetContestsWithBodyWithResponse request with any body
	PublicGetContestsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PublicGetContestsResponse, error)

	PublicGetContestsWithResponse(ctx context.Context, body PublicGetContestsJSONRequestBody, reqEditors ...RequestEditorFn) (*PublicGetContestsResponse, error)

	// PublicGetContestByIdWithResponse request
	PublicGetContestByIdWithResponse(ctx context.Context, contestID int, reqEditors ...RequestEditorFn) (*PublicGetContestByIdResponse, error)

	// PublicGetContestProblemsWithResponse request
	PublicGetContestProblemsWithResponse(ctx context.Context, contestID int, reqEditors ...RequestEditorFn) (*PublicGetContestProblemsResponse, error)

	// PublicGetProblemsWithBodyWithResponse request with any body
	PublicGetProblemsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PublicGetProblemsResponse, error)

	PublicGetProblemsWithResponse(ctx context.Context, body PublicGetProblemsJSONRequestBody, reqEditors ...RequestEditorFn) (*PublicGetProblemsResponse, error)

	// PublicGetProblemByIdWithResponse request
	PublicGetProblemByIdWithResponse(ctx context.Context, problemID int, reqEditors ...RequestEditorFn) (*PublicGetProblemByIdResponse, error)

	// PublicGetProblemEducationWithResponse request
	PublicGetProblemEducationWithResponse(ctx context.Context, problemID int, reqEditors ...RequestEditorFn) (*PublicGetProblemEducationResponse, error)

	// PublicGetProblemStatementWithResponse request
	PublicGetProblemStatementWithResponse(ctx context.Context, problemID int, params *PublicGetProblemStatementParams, reqEditors ...RequestEditorFn) (*PublicGetProblemStatementResponse, error)

	// PublicGetProblemStatementVariantsWithResponse request
	PublicGetProblemStatementVariantsWithResponse(ctx context.Context, problemID int, reqEditors ...RequestEditorFn) (*PublicGetProblemStatementVariantsResponse, error)

	// PublicGetProblemTagsWithResponse request
	PublicGetProblemTagsWithResponse(ctx context.Context, problemID int, reqEditors ...RequestEditorFn) (*PublicGetProblemTagsResponse, error)

	// PublicGetPlatformStatsWithResponse request
	PublicGetPlatformStatsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*PublicGetPlatformStatsResponse, error)

	// PublicGetSubmissionsWithBodyWithResponse request with any body
	PublicGetSubmissionsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PublicGetSubmissionsResponse, error)

	PublicGetSubmissionsWithResponse(ctx context.Context, body PublicGetSubmissionsJSONRequestBody, reqEditors ...RequestEditorFn) (*PublicGetSubmissionsResponse, error)

	// PublicGetTagsWithResponse request
	PublicGetTagsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*PublicGetTagsResponse, error)

	// PublicGetUsersWithBodyWithResponse request with any body
	PublicGetUsersWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PublicGetUsersResponse, error)

	PublicGetUsersWithResponse(ctx context.Context, body PublicGetUsersJSONRequestBody, reqEditors ...RequestEditorFn) (*PublicGetUsersResponse, error)
}

type PublicGetContestsResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *ContestSearchResult
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r PublicGetContestsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PublicGetContestsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PublicGetContestsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PublicGetContestByIdResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *ApiContest
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r PublicGetContestByIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PublicGetContestByIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PublicGetContestByIdResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PublicGetContestProblemsResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *[]ScoredProblem
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r PublicGetContestProblemsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PublicGetContestProblemsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PublicGetContestProblemsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PublicGetProblemsResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *ProblemSearchResult
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r PublicGetProblemsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PublicGetProblemsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PublicGetProblemsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PublicGetProblemByIdResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *ApiProblem
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r PublicGetProblemByIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PublicGetProblemByIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PublicGetProblemByIdResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PublicGetProblemEducationResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *ProblemEducationBundle
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r PublicGetProblemEducationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PublicGetProblemEducationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PublicGetProblemEducationResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PublicGetProblemStatementResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *ProblemStatementContent
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r PublicGetProblemStatementResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PublicGetProblemStatementResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PublicGetProblemStatementResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PublicGetProblemStatementVariantsResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *[]StatementVariant
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r PublicGetProblemStatementVariantsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PublicGetProblemStatementVariantsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PublicGetProblemStatementVariantsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PublicGetProblemTagsResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *[]Tag
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r PublicGetProblemTagsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PublicGetProblemTagsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PublicGetProblemTagsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PublicGetPlatformStatsResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *map[string]int64
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r PublicGetPlatformStatsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PublicGetPlatformStatsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PublicGetPlatformStatsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PublicGetSubmissionsResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *Submissions
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r PublicGetSubmissionsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PublicGetSubmissionsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PublicGetSubmissionsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PublicGetTagsResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *[]Tag
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r PublicGetTagsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PublicGetTagsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PublicGetTagsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PublicGetUsersResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *UsersGetOutputBody
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r PublicGetUsersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PublicGetUsersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PublicGetUsersResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// PublicGetContestsWithBodyWithResponse request with arbitrary body returning *PublicGetContestsResponse
func (c *ClientWithResponses) PublicGetContestsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PublicGetContestsResponse, error) {
	rsp, err := c.PublicGetContestsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePublicGetContestsResponse(rsp)
}

func (c *ClientWithResponses) PublicGetContestsWithResponse(ctx context.Context, body PublicGetContestsJSONRequestBody, reqEditors ...RequestEditorFn) (*PublicGetContestsResponse, error) {
	rsp, err := c.PublicGetContests(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePublicGetContestsResponse(rsp)
}

// PublicGetContestByIdWithResponse request returning *PublicGetContestByIdResponse
func (c *ClientWithResponses) PublicGetContestByIdWithResponse(ctx context.Context, contestID int, reqEditors ...RequestEditorFn) (*PublicGetContestByIdResponse, error) {
	rsp, err := c.PublicGetContestById(ctx, contestID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePublicGetContestByIdResponse(rsp)
}

// PublicGetContestProblemsWithResponse request returning *PublicGetContestProblemsResponse
func (c *ClientWithResponses) PublicGetContestProblemsWithResponse(ctx context.Context, contestID int, reqEditors ...RequestEditorFn) (*PublicGetContestProblemsResponse, error) {
	rsp, err := c.PublicGetContestProblems(ctx, contestID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePublicGetContestProblemsResponse(rsp)
}

// PublicGetProblemsWithBodyWithResponse request with arbitrary body returning *PublicGetProblemsResponse
func (c *ClientWithResponses) PublicGetProblemsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PublicGetProblemsResponse, error) {
	rsp, err := c.PublicGetProblemsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePublicGetProblemsResponse(rsp)
}

func (c *ClientWithResponses) PublicGetProblemsWithResponse(ctx context.Context, body PublicGetProblemsJSONRequestBody, reqEditors ...RequestEditorFn) (*PublicGetProblemsResponse, error) {
	rsp, err := c.PublicGetProblems(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePublicGetProblemsResponse(rsp)
}

// PublicGetProblemByIdWithResponse request returning *PublicGetProblemByIdResponse
func (c *ClientWithResponses) PublicGetProblemByIdWithResponse(ctx context.Context, problemID int, reqEditors ...RequestEditorFn) (*PublicGetProblemByIdResponse, error) {
	rsp, err := c.PublicGetProblemById(ctx, problemID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePublicGetProblemByIdResponse(rsp)
}

// PublicGetProblemEducationWithResponse request returning *PublicGetProblemEducationResponse
func (c *ClientWithResponses) PublicGetProblemEducationWithResponse(ctx context.Context, problemID int, reqEditors ...RequestEditorFn) (*PublicGetProblemEducationResponse, error) {
	rsp, err := c.PublicGetProblemEducation(ctx, problemID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePublicGetProblemEducationResponse(rsp)
}

// PublicGetProblemStatementWithResponse request returning *PublicGetProblemStatementResponse
func (c *ClientWithResponses) PublicGetProblemStatementWithResponse(ctx context.Context, problemID int, params *PublicGetProblemStatementParams, reqEditors ...RequestEditorFn) (*PublicGetProblemStatementResponse, error) {
	rsp, err := c.PublicGetProblemStatement(ctx, problemID, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePublicGetProblemStatementResponse(rsp)
}

// PublicGetProblemStatementVariantsWithResponse request returning *PublicGetProblemStatementVariantsResponse
func (c *ClientWithResponses) PublicGetProblemStatementVariantsWithResponse(ctx context.Context, problemID int, reqEditors ...RequestEditorFn) (*PublicGetProblemStatementVariantsResponse, error) {
	rsp, err := c.PublicGetProblemStatementVariants(ctx, problemID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePublicGetProblemStatementVariantsResponse(rsp)
}

// PublicGetProblemTagsWithResponse request returning *PublicGetProblemTagsResponse
func (c *ClientWithResponses) PublicGetProblemTagsWithResponse(ctx context.Context, problemID int, reqEditors ...RequestEditorFn) (*PublicGetProblemTagsResponse, error) {
	rsp, err := c.PublicGetProblemTags(ctx, problemID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePublicGetProblemTagsResponse(rsp)
}

// PublicGetPlatformStatsWithResponse request returning *PublicGetPlatformStatsResponse
func (c *ClientWithResponses) PublicGetPlatformStatsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*PublicGetPlatformStatsResponse, error) {
	rsp, err := c.PublicGetPlatformStats(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePublicGetPlatformStatsResponse(rsp)
}

// PublicGetSubmissionsWithBodyWithResponse request with arbitrary body returning *PublicGetSubmissionsResponse
func (c *ClientWithResponses) PublicGetSubmissionsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PublicGetSubmissionsResponse, error) {
	rsp, err := c.PublicGetSubmissionsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePublicGetSubmissionsResponse(rsp)
}

func (c *ClientWithResponses) PublicGetSubmissionsWithResponse(ctx context.Context, body PublicGetSubmissionsJSONRequestBody, reqEditors ...RequestEditorFn) (*PublicGetSubmissionsResponse, error) {
	rsp, err := c.PublicGetSubmissions(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePublicGetSubmissionsResponse(rsp)
}

// PublicGetTagsWithResponse request returning *PublicGetTagsResponse
func (c *ClientWithResponses) PublicGetTagsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*PublicGetTagsResponse, error) {
	rsp, err := c.PublicGetTags(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePublicGetTagsResponse(rsp)
}

// PublicGetUsersWithBodyWithResponse request with arbitrary body returning *PublicGetUsersResponse
func (c *ClientWithResponses) PublicGetUsersWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PublicGetUsersResponse, error) {
	rsp, err := c.PublicGetUsersWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePublicGetUsersResponse(rsp)
}

func (c *ClientWithResponses) PublicGetUsersWithResponse(ctx context.Context, body PublicGetUsersJSONRequestBody, reqEditors ...RequestEditorFn) (*PublicGetUsersResponse, error) {
	rsp, err := c.PublicGetUsers(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePublicGetUsersResponse(rsp)
}

// ParsePublicGetContestsResponse parses an HTTP response from a PublicGetContestsWithResponse call
func ParsePublicGetContestsResponse(rsp *http.Response) (*PublicGetContestsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PublicGetContestsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ContestSearchResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParsePublicGetContestByIdResponse parses an HTTP response from a PublicGetContestByIdWithResponse call
func ParsePublicGetContestByIdResponse(rsp *http.Response) (*PublicGetContestByIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PublicGetContestByIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ApiContest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParsePublicGetContestProblemsResponse parses an HTTP response from a PublicGetContestProblemsWithResponse call
func ParsePublicGetContestProblemsResponse(rsp *http.Response) (*PublicGetContestProblemsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PublicGetContestProblemsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []ScoredProblem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParsePublicGetProblemsResponse parses an HTTP response from a PublicGetProblemsWithResponse call
func ParsePublicGetProblemsResponse(rsp *http.Response) (*PublicGetProblemsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PublicGetProblemsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ProblemSearchResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParsePublicGetProblemByIdResponse parses an HTTP response from a PublicGetProblemByIdWithResponse call
func ParsePublicGetProblemByIdResponse(rsp *http.Response) (*PublicGetProblemByIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PublicGetProblemByIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ApiProblem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParsePublicGetProblemEducationResponse parses an HTTP response from a PublicGetProblemEducationWithResponse call
func ParsePublicGetProblemEducationResponse(rsp *http.Response) (*PublicGetProblemEducationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PublicGetProblemEducationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ProblemEducationBundle
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParsePublicGetProblemStatementResponse parses an HTTP response from a PublicGetProblemStatementWithResponse call
func ParsePublicGetProblemStatementResponse(rsp *http.Response) (*PublicGetProblemStatementResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PublicGetProblemStatementResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ProblemStatementContent
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParsePublicGetProblemStatementVariantsResponse parses an HTTP response from a PublicGetProblemStatementVariantsWithResponse call
func ParsePublicGetProblemStatementVariantsResponse(rsp *http.Response) (*PublicGetProblemStatementVariantsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PublicGetProblemStatementVariantsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []StatementVariant
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParsePublicGetProblemTagsResponse parses an HTTP response from a PublicGetProblemTagsWithResponse call
func ParsePublicGetProblemTagsResponse(rsp *http.Response) (*PublicGetProblemTagsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PublicGetProblemTagsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Tag
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParsePublicGetPlatformStatsResponse parses an HTTP response from a PublicGetPlatformStatsWithResponse call
func ParsePublicGetPlatformStatsResponse(rsp *http.Response) (*PublicGetPlatformStatsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PublicGetPlatformStatsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest map[string]int64
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParsePublicGetSubmissionsResponse parses an HTTP response from a PublicGetSubmissionsWithResponse call
func ParsePublicGetSubmissionsResponse(rsp *http.Response) (*PublicGetSubmissionsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PublicGetSubmissionsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Submissions
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParsePublicGetTagsResponse parses an HTTP response from a PublicGetTagsWithResponse call
func ParsePublicGetTagsResponse(rsp *http.Response) (*PublicGetTagsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PublicGetTagsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Tag
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParsePublicGetUsersResponse parses an HTTP response from a PublicGetUsersWithResponse call
func ParsePublicGetUsersResponse(rsp *http.Response) (*PublicGetUsersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PublicGetUsersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest UsersGetOutputBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}
